### ISSUE TITLE
怎么访问啊，后台怎么访问，报错了

### ISSUE THREAD

**Issue by devkeep163** [dairoot/ChatGPT-Mirror#10]
报错：{"error":"Cannot convert undefined or null to object"}
![image](https://github.com/dairoot/ChatGPT-Mirror/assets/165616022/42314334-92f1-4f1f-a038-119a8f779dec)

**Comment by devkeep163** [comment]
![image](https://github.com/dairoot/ChatGPT-Mirror/assets/165616022/f50d879c-7f5f-4c58-bf87-c932337841e9)

**Comment by dairoot** [comment]
`docker compose pull` 更新下镜像，重新运行
