### ISSUE TITLE
不知道发生了什么，用户登录之后，进入到聊天页，马上就跳转到您这个github项目了

### ISSUE THREAD

**Issue by wuguokai** [dairoot/ChatGPT-Mirror#11]
后台日志和浏览器截图
<img width="1908" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/30334643/0b22746c-54f4-4bda-8393-e845b56e7986">
<img width="1418" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/30334643/51d27f73-0e4c-4a4c-9fc7-4bce23164175">

**Comment by wuguokai** [comment]
admin用户可以正常登录到后台进行配置

**Comment by dairoot** [comment]
打开f12 ，就会跳转

**Comment by wuguokai** [comment]
哈哈哈，好吧，我因为是刚部署调试，所以都会打开控制台看有没有报错。多谢

**Comment by dairoot** [comment]
我看看要不要去掉跳转
