### ISSUE TITLE
大神能不能写个更详细的教学

### ISSUE THREAD

**Issue by sebastian0619** [dairoot/ChatGPT-Mirror#12]
大神能不能写个更详细的教学，包括wrangle.toml里面的数据库是要用自己的吗？以及如果在宝塔中怎么应用这个nginx等
谢谢QuQ

**Comment by dairoot** [comment]
用的是本地数据库 sqlite

**Comment by xiaotao0304** [comment]
我运行docker配置文件的时候提示我 没有key

**Comment by dairoot** [comment]
@xiaotao0304 截图

**Comment by dairoot** [comment]
https://dairoot.cn/2024/07/02/install-chatgpt-mirror/
@sebastian0619 小白级教程

**Comment by xiaotao0304** [comment]
[cid:41fd208d-4ab0-4eb2-9aab-d2db6ace3619]
________________________________
发件人: dai ***@***.***>
发送时间: 2024年7月2日 18:01
收件人: dairoot/ChatGPT-Mirror ***@***.***>
抄送: xiaotao0304 ***@***.***>; Mention ***@***.***>
主题: Re: [dairoot/ChatGPT-Mirror] 大神能不能写个更详细的教学 (Issue #12)


https://dairoot.cn/2024/07/02/install-chatgpt-mirror/

@sebastian0619<https://github.com/sebastian0619> 小白级教程

**Comment by xiaotao0304** [comment]
卡在这一步不动了[cid:5fc7ceeb-4026-43fc-81b8-528af3afd985]
________________________________
发件人: dai ***@***.***>
发送时间: 2024年7月2日 18:01
收件人: dairoot/ChatGPT-Mirror ***@***.***>
抄送: xiaotao0304 ***@***.***>; Mention ***@***.***>
主题: Re: [dairoot/ChatGPT-Mirror] 大神能不能写个更详细的教学 (Issue #12)


https://dairoot.cn/2024/07/02/install-chatgpt-mirror/

@sebastian0619<https://github.com/sebastian0619> 小白级教程
