### ISSUE TITLE
对话报错了，Our systems have detected unusual activity coming from your system. Please try again later.

### ISSUE THREAD

**Issue by wuguokai** [dairoot/ChatGPT-Mirror#13]
登录配置一切正常，但是对话就报错，换了一个服务器也是一样的问题。
<img width="860" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/30334643/dc753ef8-8179-4508-b52c-9aea97084e23">

**Comment by dairoot** [comment]
plus 账号不太稳定，我抽空优化一下。可以先用3.5账号。3.5的账号也是有gpt4的

**Comment by dairoot** [comment]
@wuguokai plus账户 对话问题解决了

**Comment by wuguokai** [comment]
<img width="1067" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/30334643/80eed580-1e99-4a90-b944-a60fd3e5296d">

**Comment by dairoot** [comment]
刷新一下页面缓存

**Comment by wuguokai** [comment]
刷新缓存可以了，不过大佬，是不是plus账号可以，team账号不支持呀。我用的team账号好像有点问题。
<img width="1274" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/30334643/dadf6cc5-c45a-44ca-b61e-b34dd8fe0e07">

**Comment by dairoot** [comment]
已解决
