### ISSUE TITLE
最新版本镜像：1.出验证码了；2.文件上传问题；3.反代端口问题

### ISSUE THREAD

**Issue by sebastian0619** [dairoot/ChatGPT-Mirror#18]
1. 出旋转图片的验证码
<img width="1054" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/39752847/9f02c622-d38d-4440-9df1-84856d56419a">
如图，这个是我已经做完的旋转图片的验证，大阪服务器和美国服务器均出现。

2. 另就文件上传，见下图。通过本项目传送的文件，很像没有被传到gpt的服务器，导致gpt无法读取。但通过官方app则正常传入了，判断应该不是服务器波动引起？：
<img width="993" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/39752847/e07ccbd5-88ef-4d90-a3c1-a14c29866d74">
<img width="1117" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/39752847/3b5e7f9e-15a8-4d7b-a800-75c05f5e3d0d">

3. 反代端口
使用宝塔面板，参照教程设置反代。端口8787。
<img width="308" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/39752847/a4e72b2e-a02e-48d3-a5d5-207d3cfcb108">
容器我设置了3个worker。很像因为宝塔反代只指定了8787，所以只有一个worker在工作。但按照下方设置端口范围后，依然只有一个worker在工作
<img width="314" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/39752847/4cdb10f5-d2a6-4119-85b3-61a8ab08f2b2">

**Comment by dairoot** [comment]
1. 验证码一般只会出现一次。（不要打开f12，f12 有一定概率会弹出验证码）
2. 文件回复问题，我处理下
3. 反代端口，自行查阅nginx和宝塔相关文档

**Comment by dairoot** [comment]
第二个问题，跟服务器ip有关，我自己的服务器也出现同样的。
然后本地ss这台服务器。用官网询问，也是无法解析文件 @sebastian0619 
<img width="560" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/10009878/02f0cf29-256b-454a-8411-fb00364cbf3a">

**Comment by sebastian0619** [comment]
> 第二个问题，跟服务器ip有关，我自己的服务器也出现同样的。 然后本地ss这台服务器。用官网询问，也是无法解析文件 @sebastian0619
> 
> <img alt="image" width="564" src="https://private-user-images.githubusercontent.com/10009878/345847554-9444a146-5209-4749-b45d-35051fed57bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDAxODYsIm5iZiI6MTcyMDA5OTg4NiwicGF0aCI6Ii8xMDAwOTg3OC8zNDU4NDc1NTQtOTQ0NGExNDYtNTIwOS00NzQ5LWI0NWQtMzUwNTFmZWQ1N2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEzMzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NDc5OTNjODc5ZjM0ODhjZjE2NjE4YWJhOWExZjc1Yjk0MjhlZDM3MWYxZGVhMWRlYTQ2Zjk1YTlmZWZiYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.phC8Zzo27lo_B0BhG9-X823bckVptRJf4LsTQsSoVlA">

目前看来靠谱的解决方案可能就是换机子、或者机子换ip？

**Comment by dairoot** [comment]
是的，我看了其他网友的机器，不会出现这个问题 @sebastian0619
