### ISSUE TITLE
现在是不行了吗，搭建完之后现在是这样

### ISSUE THREAD

**Issue by OceanLiu-L** [dairoot/ChatGPT-Mirror#20]
<img width="887" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/39451903/60d838f1-50c5-41b0-9b2f-8941ace3a2cc">

**Comment by OceanLiu-L** [comment]
> 服务器ip问题，换个ip

好的，感谢大佬，我来试试

**Comment by OceanLiu-L** [comment]
确实是ip问题，用了warp代理，可以了，但是速率太慢，warp还是不行啊

**Comment by dairoot** [comment]
@OceanLiu-L 麻烦首页加一下我的QQ，了解一下使用warp代理导致的问题
