### ISSUE TITLE
每一句话都弹验证码，旋转图像那种，正常吗

### ISSUE THREAD

**Issue by Potato-lover** [dairoot/ChatGPT-Mirror#21]

**Comment by Potato-lover** [comment]
主要是有时候输入完验证码还没用，叉掉之后按回车又弹验证码

**Comment by dairoot** [comment]
跟ip 有关，用久估计不会了，后面考虑接入 https://www.capsolver.com/zh

**Comment by mewtwov** [comment]
> 跟ip 有关，用久估计不会了，后面考虑接入 https://www.capsolver.com/zh

希望尽快接入🙏🙏🙏

**Comment by dairoot** [comment]
> > 跟ip 有关，用久估计不会了，后面考虑接入 https://www.capsolver.com/zh
> 
> 希望尽快接入🙏🙏🙏

@mewtwov  CapSolver 最少充值需要 6刀 😂，怕没几个会用

**Comment by dairoot** [comment]
@Potato-lover @mewtwov 弹验证码问题已修复。
