### ISSUE TITLE
登陆白屏，docker部署

### ISSUE THREAD

**Issue by monkey-sking** [dairoot/ChatGPT-Mirror#22]
![image](https://github.com/user-attachments/assets/9c45e5cf-c260-4e98-8761-245fad633556)

![image](https://github.com/user-attachments/assets/b6c2e0aa-dde3-4fc5-8c8c-46bf52286b7e)

**Comment by dairoot** [comment]
尝试清空缓存

**Comment by monkey-sking** [comment]
> 是否是最新镜像，尝试清空缓存
项目、docker重新弄好多几次

**Comment by dairoot** [comment]
@monkey-sking 加一下群里，反馈
