### ISSUE TITLE
可否 让docker 配置 http_proxy 也能达到海外VPS 一样效果

### ISSUE THREAD

**Issue by 1115348410** [dairoot/ChatGPT-Mirror#25]
可否 让docker 配置 http_proxy 也能达到海外VPS 一样效果

**Comment by moonzjs** [comment]
暂不支持，本地可以使用全局代理形式

**Comment by dairoot** [comment]
> 可否 让docker 配置 http_proxy 也能达到海外VPS 一样效果

暂不支持，本地可以使用全局代理形式

**Comment by eaglexiang** [comment]
关注下，看啥时候能有 http_proxy 支持

**Comment by dairoot** [comment]
> 关注下，看啥时候能有 http_proxy 支持

@eaglexiang 灰度测试中，加一下群里办法测试下

**Comment by dairoot** [comment]
已支持
