### ISSUE TITLE
部署后访问空白

### ISSUE THREAD

**Issue by ghostman-git** [dairoot/ChatGPT-Mirror#26]
![image](https://github.com/user-attachments/assets/30beb6e7-6553-402d-bc9c-f2951f6dd301)

![image](https://github.com/user-attachments/assets/cae07c48-606f-4be8-aee4-b9a30b447b21)

![image](https://github.com/user-attachments/assets/761d5e0d-c1d8-473b-9c8f-b7e651135001)

**Comment by dairoot** [comment]
稍等，刚刚改了东西，引起了

**Comment by dairoot** [comment]
@ghostman-git @yaoyaochil  空白问题修复了，更新一下镜像
```bash
docker compose pull
```
