### ISSUE TITLE
配置代理后有流量，但是网页卡转圈

### ISSUE THREAD

**Issue by L1bws** [dairoot/ChatGPT-Mirror#27]
![image](https://github.com/user-attachments/assets/9def803c-f613-482c-b4fc-36082f8ca4a2)
一直转圈，无法下一步

![image](https://github.com/user-attachments/assets/3bec82cc-6d1e-4ac8-b6f7-6241c0ec7e47)
xray有流量，这个节点也可以连接gpt

**Comment by L1bws** [comment]
![image](https://github.com/user-attachments/assets/3c153f6d-06ad-4851-bd2f-7f6e0f981d5b)
Docker的日志

**Comment by dairoot** [comment]
核对返回的 ip 是否为代理 ip
```bash
curl -s http://127.0.0.1:50001/test?username=管理后台账号
```

https://github.com/dairoot/ChatGPT-Mirror/blob/main/docs/faq-cn.md

**Comment by L1bws** [comment]
非常感谢，我更换了节点就能访问了，没想到cf给我分配的是香港的ip
