### ISSUE TITLE
禁止访问，弹攻击模式了

### ISSUE THREAD

**Issue by L1bws** [dairoot/ChatGPT-Mirror#29]
![image](https://github.com/user-attachments/assets/317ecf8e-a124-4f08-9470-d1cfa7aa1fd7)
貌似特征被查出来了？换IP和账号都不奏效了

**Comment by dairoot** [comment]
这个应该是 chatgpt 官方临时挂了

**Comment by L1bws** [comment]
> 这个应该是 chatgpt 官方临时挂了

确实，今天下午又好了，感谢感谢
