### ISSUE TITLE
403、弹cf的质询/交互验证码、被阻止访问

### ISSUE THREAD

**Issue by L1bws** [dairoot/ChatGPT-Mirror#31]
![image](https://github.com/user-attachments/assets/c23a4255-3250-4e9e-8dec-d1bbfa0ee399)
这个是登录Plus账号时403，如果刷新几次会直接出现cf的页面质询验证码，但是加载不出来，再刷新几次又可以进去了

有时候换浏览器或者开个无痕也可以进去，或者等一会又能进去，免费和Plus账号都一样

有时候重启镜像也可以解决问题，但是只要到晚上9点后或者早上8点前就会出现，怎么切都解决不了，登录次数多了直接弹CF的阻止

**Comment by L1bws** [comment]
去后台刷新Token也是一样的，不是403就是连接失败，而且有时候直接跳转到根路径直接显示这个
![image](https://github.com/user-attachments/assets/00a5a619-0ac4-4123-8881-8257bedd4ff2)

**Comment by dairoot** [comment]
更换ip
