### ISSUE TITLE
Can you guide me please how to use chatgpt login free api

### ISSUE THREAD

**Issue by Niansuh** [dairoot/ChatGPT-Mirror#33]
Can you guide me please how to use chatgpt login free api

Thanks for making this ChatGPT-Mirror

**Comment by dairoot** [comment]
Sorry, I haven't created an English version of the tutorial. However, you can use a translation tool to translate the article and follow the instructions. Here’s the tutorial link: https://github.com/dairoot/ChatGPT-Mirror/blob/main/docs/deploy.md.

**Comment by rkihacker** [comment]
same issue... can you please add chatgpt login free api without adding accounts
