### ISSUE TITLE
status: 429

### ISSUE THREAD

**Issue by qwert12asd** [dairoot/ChatGPT-Mirror#34]
你好，请问出现status: 429提示，是哪里出问题了吗，就是输入token后显示这个错误。
希望可以得到回复，谢谢啦

**Comment by dairoot** [comment]
每次都会 429 吗

**Comment by qwert12asd** [comment]
谢谢，这个问题已经解决了（后面重启了docker就好了）

我问一下一定要配置https吗，不然登录之后会提示data:请配置https
&nbsp;


もったいない
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月16日(星期三) 晚上10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dairoot/ChatGPT-Mirror] status: 429 (Issue #34)














 
每次都会 429 吗

**Comment by dairoot** [comment]
是的，需要强制配置 https。下个版本会取消

**Comment by qwert12asd** [comment]
你好，请问在登录界面显示“无法使用提供的认证信息登录”，这个是什么原因吗



&nbsp;


もったいない
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月17日(星期四) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dairoot/ChatGPT-Mirror] status: 429 (Issue #34)














 
是的，需要强制配置 https。下个版本会取消
