### ISSUE TITLE
关于登录账号后网页部分缺失问题

### ISSUE THREAD

**Issue by guoyaoyao2011** [dairoot/ChatGPT-Mirror#35]
![image](https://github.com/user-attachments/assets/36e80456-3f52-4e90-9c1c-de6a0c86d6aa)
![image](https://github.com/user-attachments/assets/dc38f70f-9d1b-4155-b6ea-030f60a73bd4)
![image](https://github.com/user-attachments/assets/22b04976-6d4f-437c-93da-adf054db42f8)
由于获取文件的url错误，缺少端口号，无法正确的获取文件
所以请问如何把https://**********.com/cdn.oaistatic.com/assets/manifest-928a83fd.js替换成https://***********.com:*****/cdn.oaistatic.com/assets/manifest-928a83fd.js，谢谢

**Comment by dairoot** [comment]
暂不支持携带端口号

**Comment by guoyaoyao2011** [comment]
后续会支持吗

**Comment by guoyaoyao2011** [comment]
okok感谢

**Comment by dairoot** [comment]
已支持

**Comment by guoyaoyao2011** [comment]
okok感谢
