### ISSUE TITLE
请求失败, 网络异常

### ISSUE THREAD

**Issue by xiaokuncloud** [dairoot/ChatGPT-Mirror#37]
搭建没问题，然后录入token后立马cf安装了wrap也不行

**Comment by xiaokuncloud** [comment]
chatgpt.com
正在验证您是否是真人。这可能需要几秒钟时间。

**Comment by dairoot** [comment]
[常见问题](https://github.com/dairoot/ChatGPT-Mirror/blob/main/docs/faq-cn.md)
