### ISSUE TITLE
卡人机验证

### ISSUE THREAD

**Issue by ikunycj** [dairoot/ChatGPT-Mirror#38]
![de88cf090ebba4c022418ac9d4b96ecc](https://github.com/user-attachments/assets/6153a4d5-e754-4d12-ac51-0c77ea392829)
输入Cookie后，卡在了人机验证这一步，请问下这个问题怎么回事？是我服务器不好吗(洛杉矶便宜服务器)

**Comment by ikunycj** [comment]
哦，并且输入cookie的一瞬间系统会提示"请求失败403"

**Comment by dairoot** [comment]
[常见问题](https://github.com/dairoot/ChatGPT-Mirror/blob/main/docs/faq-cn.md)
