### ISSUE TITLE
请问代理是否一定需要？

### ISSUE THREAD

**Issue by hnuzhoulin** [dairoot/ChatGPT-Mirror#48]
是否需要自己找一个符合openai地域的vps作为代理？

**Comment by dairoot** [comment]
只要能访问 openai就行，过盾先看：https://github.com/dairoot/ChatGPT-Mirror/blob/main/docs/faq-cn.md

过盾优先推荐使用:
```
docker compose -f docker-compose-cf5s.yml up
```
