### ISSUE TITLE
GPT 不读取图像和文档

### ISSUE THREAD

**Issue by alawyyahdan** [dairoot/ChatGPT-Mirror#49]
![image](https://github.com/user-attachments/assets/8eb40354-1d35-4e02-91db-43e402696931)

为什么GPT无法读取我上传的图片和文档？
请帮助朋友

**Comment by dairoot** [comment]
openai今早调整了策略，导致大幅度降智

**Comment by alawyyahdan** [comment]
稍后会有关于这个项目的更新吗？还是我们要等待 Openai 的通知？

**Comment by dairoot** [comment]
你尝试更新镜像，看看是否可以 正常读取图片和文档

**Comment by alawyyahdan** [comment]
我已经尝试更新图像，但它仍然是一样的，我的朋友
