### ISSUE TITLE
录入token后闪退

### ISSUE THREAD

**Issue by fengwm64** [dairoot/ChatGPT-Mirror#51]
如题，录入token后出现一个黄色提示（但是消失太快没有看清楚）紧接着闪退到登陆界面，hk地区服务器

**Comment by JantyKkum** [comment]
"1.存在cf盾，请更换ip(更改服务器 或 使用代理 或 使用warp),status: 403 Forbidden"，我也遇到了，不知道怎么解决

**Comment by fengwm64** [comment]
换为美国服务器解决了，但是存在降智问题
