### ISSUE TITLE
登录时显示["无法使用提供的认证信息登录。"]

### ISSUE THREAD

**Issue by qwert12asd** [dairoot/ChatGPT-Mirror#54]
我在登录界面输入了账号和密码之后显示：["无法使用提供的认证信息登录。"]
请问这个是什么原因吗，谢谢啦

**Comment by qwert12asd** [comment]
> 可能是token过期了？

就是我自己设置的管理员账号密码都登不进去，输入什么都是显示这个，应该需要作者帮下忙

**Comment by dairoot** [comment]
就是账号密码错误了
