### ISSUE TITLE
能够进入登录界面，但是流畅使用GPT还是需要在本地翻墙，租的是美国硅谷的服务器，请问可能是什么原因导致的呢

### ISSUE THREAD

**Issue by Dr-pipi** [dairoot/ChatGPT-Mirror#62]

**Comment by dairoot** [comment]
访问线路的问题

**Comment by Dr-pipi** [comment]
> 访问线路的问题

谢谢大佬的回复，现在存在的问题就是我不开梯子的话，GPT的页面加载不完整，也不能提问；必须开梯子才能正常使用。我试了你给的体验版就没有这个问题，如果是访问线路的问题的话，大佬有什么解决方法吗

**Comment by dairoot** [comment]
cdn 加速，比如使用 cloudflare
