### ISSUE TITLE
镜像站的网址在手机端登录之后如果gpt回答的内容过长，不能下拉继续阅读，PC端没有这个问题，请问大佬这是不是bug？

### ISSUE THREAD

**Issue by Dr-pipi** [dairoot/ChatGPT-Mirror#63]

**Comment by Dr-pipi** [comment]
我在手机端和PC端分别测试了体验站，也存在一样的问题，无法下拉内容

**Comment by Dr-pipi** [comment]
我在手机端和PC端分别测试了体验站，也存在一样的问题，无法下拉内容

**Comment by Dr-pipi** [comment]
> 你可以前往体验站点 验证你的猜想是否正确

我在手机端和PC端分别测试了体验站，也存在一样的问题，无法下拉内容

**Comment by dairoot** [comment]
我这边测试不存在你所描述的问题，可能跟你本地网络环境有关

**Comment by Dr-pipi** [comment]
> 我这边测试不存在你所描述的问题，可能跟你本地网络环境有关

我回去再试试，谢谢大佬做出这么优秀的作品
