### ISSUE TITLE
Session Token失效时间过早

### ISSUE THREAD

**Issue by Dr-pipi** [dairoot/ChatGPT-Mirror#68]
按照您的视频教程添加到后台的session token两三天就过期了，比预计的要早好多天，这可能是什么原因导致的呢。另外我目前还不清楚怎么获取refresh token，希望大佬赐教

**Comment by dairoot** [comment]
ChatGPT 官网挂了，导致token刷新异常。 更新一下镜像 
```
./deploy.sh
```

**Comment by Dr-pipi** [comment]
> ChatGPT 官网挂了，导致token刷新异常。 更新一下镜像
> 
> ```
> ./deploy.sh
> ```

大佬，我需要重新拉取镜像吗，还是直接./deploy.sh，我现在部署的就是您几天前更新的那一版

**Comment by dairoot** [comment]
> > ChatGPT 官网挂了，导致token刷新异常。 更新一下镜像
> > ```
> > ./deploy.sh
> > ```
> 
> 大佬，我需要重新拉取镜像吗，还是直接./deploy.sh，我现在部署的就是您几天前更新的那一版

./deploy.sh 就会重新拉取镜像

**Comment by Dr-pipi** [comment]
> > > ChatGPT 官网挂了，导致token刷新异常。 更新一下镜像
> > > ```
> > > ./deploy.sh
> > > ```
> > 
> > 
> > 大佬，我需要重新拉取镜像吗，还是直接./deploy.sh，我现在部署的就是您几天前更新的那一版
> 
> ./deploy.sh 就会重新拉取镜像

谢谢大佬。另外那个refresh token现在是不是不容易获取了啊，我查了很多资料都没有找到好的解决办法
