### ISSUE TITLE
出验证码了

### ISSUE THREAD

**Issue by eureka6** [dairoot/ChatGPT-Mirror#8]
断断续续提问了30次左右，出了一次人机验证，旋转图像的那种，3步完成。

那可不可以接入第三方打码平台（免费or付费）来规避呢？

或者自定义ua和指纹什么的，对这个有帮助吗？

**Comment by dairoot** [comment]
我研究一下，看能不能绕过

**Comment by dairoot** [comment]
麻烦首页加一下我的 qq。有细节需要核对下

**Comment by dairoot** [comment]
已解决

**Comment by GeoGu360** [comment]
> 已解决

老哥，请教下，这个是什么原因，是Nginx配置的有问题吗？

**Comment by dairoot** [comment]
@GeoGu360 plus 账号 还是3.5 账号

**Comment by qingyuan0o0** [comment]
今天测试,我只启用了一个工作集,因为主机内存比较小,打开时提示正在验证您是否是真人。这可能需要几秒钟时间。,再然后出现验证所用的时间比预期时间长。如果问题仍然存在，请检查您的 Internet 连接并[刷新页面]()。
会不会是因为我用caddy转发80和443到8787,并且配置了证书,但是问题依旧出现

**Comment by dairoot** [comment]
@qingyuan0o0 一般新设备会出现一次，你那边出现很多少次吗

**Comment by wuguokai** [comment]
<img width="1273" alt="image" src="https://github.com/dairoot/ChatGPT-Mirror/assets/30334643/acf16b9a-7b4b-46c3-bb43-d057fd05c0df">
我也出现了这个问题

**Comment by qingyuan0o0** [comment]
基本上每次打开这个页面都是这样

**Comment by qingyuan0o0** [comment]
![Screenshot_20240625_174300_com.yujian.ResideMenuDemo.jpg](https://github.com/dairoot/ChatGPT-Mirror/assets/18437931/d0ca319d-e7fd-4e86-8a34-657adf9a64cd)

![Screenshot_20240625_174308_com.yujian.ResideMenuDemo.jpg](https://github.com/dairoot/ChatGPT-Mirror/assets/18437931/bff64002-ccd8-41db-8112-d2956c67a17d)

目前就这个样子，而用这台主机开代理去访问，会有按钮验证是否真人

**Comment by dairoot** [comment]
首页，加我QQ

**Comment by GeoGu360** [comment]
> @GeoGu360 plus 账号 还是3.5 账号

plus的账号，

**Comment by dairoot** [comment]
@GeoGu360  plus账户 对话问题解决了. 更新一下镜像

**Comment by GeoGu360** [comment]
> @GeoGu360 plus账户 对话问题解决了. 更新一下镜像

感谢，反代可以了，可以不挂梯子了
